//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public string Department_ID { get; set; }
        public string Department_Name { get; set; }
        public string UserID { get; set; }
        public string Flag { get; set; }
        public string Department_Ref { get; set; }
        public string UserID_Ref { get; set; }
        public string CostCenter { get; set; }
        public string ShortBrand { get; set; }
    }
}
