//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_IO_Brand
    {
        public string Department_ID { get; set; }
        public string Brand_ID { get; set; }
        public Nullable<double> Percent_Brand { get; set; }
        public Nullable<double> Rent_Brand { get; set; }
        public Nullable<double> PR01 { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> COGS { get; set; }
        public Nullable<double> NOPEX { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<double> PR01_G { get; set; }
        public Nullable<double> Discount_G { get; set; }
        public Nullable<double> Area { get; set; }
        public string Site_Storage_B { get; set; }
        public string NewFC { get; set; }
        public Nullable<System.DateTime> dateSt { get; set; }
        public Nullable<System.DateTime> dateEd { get; set; }
        public int Revision { get; set; }
    }
}
