//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_IO
    {
        public string Department_ID { get; set; }
        public string Department_Name { get; set; }
        public Nullable<System.DateTime> Date_Send { get; set; }
        public Nullable<int> Revision { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Status_ID { get; set; }
        public string Cost_Number { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public Nullable<System.DateTime> Date_End { get; set; }
        public Nullable<System.DateTime> Action_Start { get; set; }
        public Nullable<System.DateTime> Action_End { get; set; }
        public Nullable<int> UserID_Save { get; set; }
        public string Detail { get; set; }
        public string Remark { get; set; }
        public string Flag_IO { get; set; }
        public string Head_Department_ID { get; set; }
        public string Head_UserID { get; set; }
        public string UserID_Ref { get; set; }
        public string Department_Ref { get; set; }
        public string SyncStatus { get; set; }
        public string Status_IO { get; set; }
        public string Version { get; set; }
        public string SiteStorage { get; set; }
        public string Type { get; set; }
        public Nullable<bool> NewFC { get; set; }
        public Nullable<int> Per_Share { get; set; }
        public string Ref_Cost_Number { get; set; }
        public Nullable<bool> NewFC_NextYear { get; set; }
        public string ReturnStatus { get; set; }
    }
}
