//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainBudget
    {
        public int Year_Budget { get; set; }
        public string Department_ID { get; set; }
        public int Detail_ID { get; set; }
        public int Revision { get; set; }
        public string Department_Type { get; set; }
        public Nullable<double> M01 { get; set; }
        public Nullable<double> M02 { get; set; }
        public Nullable<double> M03 { get; set; }
        public Nullable<double> M04 { get; set; }
        public Nullable<double> M05 { get; set; }
        public Nullable<double> M06 { get; set; }
        public Nullable<double> M07 { get; set; }
        public Nullable<double> M08 { get; set; }
        public Nullable<double> M09 { get; set; }
        public Nullable<double> M10 { get; set; }
        public Nullable<double> M11 { get; set; }
        public Nullable<double> M12 { get; set; }
        public Nullable<double> M01_O { get; set; }
        public Nullable<double> M02_O { get; set; }
        public Nullable<double> M03_O { get; set; }
        public Nullable<double> M04_O { get; set; }
        public Nullable<double> M05_O { get; set; }
        public Nullable<double> M06_O { get; set; }
        public Nullable<double> M07_O { get; set; }
        public Nullable<double> M08_O { get; set; }
        public Nullable<double> M09_O { get; set; }
        public Nullable<double> M10_O { get; set; }
        public Nullable<double> M11_O { get; set; }
        public Nullable<double> M12_O { get; set; }
        public Nullable<int> UserID_Save { get; set; }
        public Nullable<System.DateTime> Date_Save { get; set; }
        public Nullable<int> UserID_Active { get; set; }
        public Nullable<System.DateTime> Date_Active { get; set; }
        public string Status_ID { get; set; }
        public string Status_Sync { get; set; }
        public string Detail_Remark { get; set; }
        public string Department_IO_ID { get; set; }
    }
}
