//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainExpense
    {
        public string Docno { get; set; }
        public Nullable<int> Revision { get; set; }
        public Nullable<System.DateTime> Date_Send { get; set; }
        public string Status_ID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Date_Use { get; set; }
        public string Department_ID { get; set; }
        public Nullable<int> TypeBudget_ID { get; set; }
        public string Flag { get; set; }
        public string SAPRemark { get; set; }
        public string OD_Docno { get; set; }
        public string Remark { get; set; }
        public string SyncStatus { get; set; }
        public string Version { get; set; }
        public string Site_Storage { get; set; }
    }
}
