//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainExpense_Sub
    {
        public string Docno { get; set; }
        public int Detail_ID { get; set; }
        public string Detail { get; set; }
        public Nullable<double> Estimate { get; set; }
        public Nullable<double> Actual { get; set; }
        public string Brand_ID { get; set; }
        public Nullable<double> Brand_Percent { get; set; }
        public string SiteStorage { get; set; }
    }
}
