//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Online_NonAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_NonAPI
    {
        public string Docno { get; set; }
        public Nullable<System.DateTime> Date_Send { get; set; }
        public string DocStatus { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Revision { get; set; }
        public Nullable<System.DateTime> POS_Date { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string StorageWM_ID { get; set; }
        public string Channel_ID { get; set; }
        public string Transaction_Type { get; set; }
        public string Ref_Order { get; set; }
        public string Ref_Order_Sales { get; set; }
        public string Payment_Type { get; set; }
        public string Shipping_Type { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public string AddressBilling_ID_Card { get; set; }
        public string AddressBilling_FirstName { get; set; }
        public string AddressBilling_LastName { get; set; }
        public string AddressBilling_Address1 { get; set; }
        public string AddressBilling_Address2 { get; set; }
        public string AddressBilling_PostCode { get; set; }
        public string AddressBilling_Province_ID { get; set; }
        public string AddressBilling_Amphur_ID { get; set; }
        public string AddressBilling_District_ID { get; set; }
        public string AddressBilling_Tel1 { get; set; }
        public string AddressBilling_Tel2 { get; set; }
        public Nullable<bool> C_AddressShipping { get; set; }
        public string AddressShipping_FirstName { get; set; }
        public string AddressShipping_LastName { get; set; }
        public string AddressShipping_Address1 { get; set; }
        public string AddressShipping_Address2 { get; set; }
        public string AddressShipping_PostCode { get; set; }
        public string AddressShipping_Province_ID { get; set; }
        public string AddressShipping_Amphur_ID { get; set; }
        public string AddressShipping_District_ID { get; set; }
        public string AddressShipping_Tel1 { get; set; }
        public string AddressShipping_Tel2 { get; set; }
        public Nullable<int> InventoryDocID { get; set; }
        public Nullable<System.DateTime> Date_Tracking { get; set; }
        public string UserID_Tracking { get; set; }
        public Nullable<System.DateTime> Date_Print { get; set; }
        public string UserID_Print { get; set; }
        public string UserID_GetOrder { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Date_Deliverynote { get; set; }
        public string UserID_Deliverynote { get; set; }
        public Nullable<System.DateTime> Date_Check { get; set; }
        public string UserID_Check { get; set; }
        public string Flag_Check { get; set; }
        public string Note { get; set; }
        public string Ref_Data { get; set; }
        public Nullable<System.DateTime> Date_FNC { get; set; }
        public string UserID_FNC { get; set; }
        public Nullable<System.DateTime> Rvd_Money_FNC { get; set; }
        public Nullable<double> Shippingprice { get; set; }
        public string FileName { get; set; }
        public string Flag_Change { get; set; }
        public Nullable<System.DateTime> DateDeli_FNC { get; set; }
        public string UserIDDeli_FNC { get; set; }
        public string Non_Report { get; set; }
        public string WMS_ShipmentID { get; set; }
        public string Type_Document { get; set; }
        public Nullable<bool> Insert_Account { get; set; }
    }
}
