//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Online_NonAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_NonAPI_Item
    {
        public string Docno { get; set; }
        public string No { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> PromoID { get; set; }
        public Nullable<double> retailPrice { get; set; }
        public Nullable<double> NetPrice { get; set; }
        public string Get_Product { get; set; }
        public string Tracking_No { get; set; }
        public string Box_ID { get; set; }
        public Nullable<int> Unit_Box { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string Promoition_ID { get; set; }
        public string Flag_Check { get; set; }
        public string Send_Item { get; set; }
        public string Non_Report { get; set; }
    }
}
