//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Online_NonAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Online_NonAPIEntities : DbContext
    {
        public Online_NonAPIEntities()
            : base("name=Online_NonAPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Form_NonAPI> Form_NonAPI { get; set; }
        public virtual DbSet<Form_NonAPI_Item> Form_NonAPI_Item { get; set; }
        public virtual DbSet<Type_Channel> Type_Channel { get; set; }
    }
}
