//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Online_NonAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Channel
    {
        public string Channel_ID { get; set; }
        public string Channel_Name { get; set; }
        public string Flag_Active { get; set; }
        public string SiteID { get; set; }
        public string terminalID { get; set; }
        public string refCode { get; set; }
        public string Flag_Show { get; set; }
        public string Type_Process { get; set; }
        public string Flag_Transaction { get; set; }
        public string PaymentTypeCode { get; set; }
        public Nullable<bool> Shared_Offline { get; set; }
        public string Channel_Group { get; set; }
    }
}
