//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Whale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        public int Box_ID { get; set; }
        public string Box_Name { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> Flag_Active { get; set; }
    }
}
