//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Whale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public int Channel_ID { get; set; }
        public string Channel_Name { get; set; }
        public string Flag_Active { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> terminalID { get; set; }
        public string refCode { get; set; }
        public Nullable<bool> Flag_Show { get; set; }
        public string Type_Transfer { get; set; }
        public string Type_Transaction { get; set; }
        public Nullable<bool> Flag_Transaction { get; set; }
        public Nullable<bool> Flag_Upload { get; set; }
        public Nullable<bool> Flag_Shipping { get; set; }
        public string PaymentTypeCode { get; set; }
        public Nullable<bool> Shared_Offline { get; set; }
        public string Pickup_ID { get; set; }
        public string Pickup_Name { get; set; }
        public string Pickup_Address { get; set; }
        public string Pickup_City { get; set; }
        public string Pickup_Province { get; set; }
        public string Pickup_Postcode { get; set; }
        public string Pickup_Phone { get; set; }
        public string Pickup_Email { get; set; }
        public string Channel_Group { get; set; }
        public string Flag_Channel_Xclusive { get; set; }
    }
}
