//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Whale
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int City_ID { get; set; }
        public string City_Name { get; set; }
        public int Province_ID { get; set; }
    }
}
