//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Whale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customer_ID { get; set; }
        public int StorageWM_ID { get; set; }
        public int Channel_ID { get; set; }
        public string refCode { get; set; }
        public string Customer_Name { get; set; }
        public string SAP_Channel { get; set; }
        public string SAP_Company { get; set; }
        public string SAP_Storage_Transfer { get; set; }
        public string SAP_Storage_Received { get; set; }
        public string SAP_Site { get; set; }
        public string DC { get; set; }
        public Nullable<int> ECommerce_Channel_ID { get; set; }
    }
}
