//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Whale
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder_Item
    {
        public string Docno { get; set; }
        public string No { get; set; }
        public string SKU { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<double> RetailPrice { get; set; }
        public Nullable<double> NetPrice { get; set; }
        public string Status { get; set; }
        public string Trackingno { get; set; }
        public Nullable<bool> Boxed { get; set; }
        public Nullable<int> Box_ID { get; set; }
        public Nullable<int> Box_No { get; set; }
        public Nullable<bool> Flag_Return { get; set; }
        public string Vouchercode { get; set; }
        public Nullable<double> Packingcost { get; set; }
        public Nullable<double> Shippingfee { get; set; }
        public Nullable<double> Paymentfee { get; set; }
        public Nullable<double> Commissionfee { get; set; }
    }
}
