//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_ForeCast
    {
        public string ForecastID { get; set; }
        public string Year { get; set; }
        public string DepartmentID { get; set; }
        public string GroupNameID { get; set; }
        public Nullable<double> M01 { get; set; }
        public Nullable<double> M02 { get; set; }
        public Nullable<double> M03 { get; set; }
        public Nullable<double> M04 { get; set; }
        public Nullable<double> M05 { get; set; }
        public Nullable<double> M06 { get; set; }
        public Nullable<double> M07 { get; set; }
        public Nullable<double> M08 { get; set; }
        public Nullable<double> M09 { get; set; }
        public Nullable<double> M10 { get; set; }
        public Nullable<double> M11 { get; set; }
        public Nullable<double> M12 { get; set; }
        public string UserID_Save { get; set; }
        public string SaveID { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> ActiveStatus { get; set; }
        public string UserID_Active { get; set; }
        public string ActiveID { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public string Flag { get; set; }
        public string Remark { get; set; }
    }
}
