//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_HApprove
    {
        public string departmentID { get; set; }
        public string department_ { get; set; }
        public string UserID { get; set; }
        public string EmpID { get; set; }
        public string Flag { get; set; }
        public string Cost { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string UserID_Save { get; set; }
        public string EmpChk { get; set; }
        public string UserID_Chk { get; set; }
        public string DepartmentChk { get; set; }
        public string Sta { get; set; }
        public string RemarkIO { get; set; }
        public string Detail { get; set; }
        public string Status_Department { get; set; }
        public string statusIO { get; set; }
        public string BrandForWS { get; set; }
        public string FlagForWS { get; set; }
        public string FlagForWF { get; set; }
        public string ID_Brand { get; set; }
        public string UserIDHead_OnlyFC { get; set; }
        public string Head_Department { get; set; }
        public string Head_Department_UserID { get; set; }
        public string Remark { get; set; }
        public string Note { get; set; }
        public string FlagAddEDate { get; set; }
        public string Type_BrandGroup { get; set; }
        public string ReserveGroupCompanyID { get; set; }
        public string Purchase_Chk { get; set; }
        public string Purchase_UserID_Chk { get; set; }
        public string Flag_PB { get; set; }
        public string Comp_Group { get; set; }
        public string Group_Conso { get; set; }
        public string Flag_Clear { get; set; }
        public string Flag_FCBonus { get; set; }
        public string Flag_VGroup { get; set; }
        public string UserID_Shoes { get; set; }
        public string SAP_Ref { get; set; }
    }
}
