//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_HApprove_Profitcenter
    {
        public string DepartmentID { get; set; }
        public string Depart_Short { get; set; }
        public string ComCode { get; set; }
        public string Profit_Offline { get; set; }
        public string CostCenter_Offline { get; set; }
        public string Profit_Online { get; set; }
        public string CostCenter_Online { get; set; }
    }
}
