//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Tax
    {
        public string CustomerCode { get; set; }
        public string NameTax { get; set; }
        public string BranchCode { get; set; }
        public string TaxID { get; set; }
        public string Address1 { get; set; }
        public string lane1 { get; set; }
        public string Road1 { get; set; }
        public string Zone1 { get; set; }
        public string Area1 { get; set; }
        public string Postal1 { get; set; }
        public string phone1 { get; set; }
        public string fax1 { get; set; }
        public string Province1 { get; set; }
        public string Branch_Acc { get; set; }
    }
}
