//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public int departmentID { get; set; }
        public int divisionID { get; set; }
        public string department_ { get; set; }
        public string Flag { get; set; }
    }
}
