//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int userID { get; set; }
        public Nullable<int> masterID { get; set; }
        public string TypeEmployee { get; set; }
        public string uCode { get; set; }
        public Nullable<byte> title_ { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string eName { get; set; }
        public string eSurname { get; set; }
        public string nick { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string username_ { get; set; }
        public string password_ { get; set; }
        public Nullable<int> uLevel { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public Nullable<int> educationID { get; set; }
        public Nullable<int> provinceID { get; set; }
        public Nullable<int> placeID { get; set; }
        public Nullable<int> positionID { get; set; }
        public string pNote { get; set; }
        public Nullable<int> departmentID { get; set; }
        public string brandID { get; set; }
        public Nullable<int> posts { get; set; }
        public Nullable<int> comments { get; set; }
        public Nullable<int> logins { get; set; }
        public Nullable<System.DateTime> lastLogin { get; set; }
        public string ip { get; set; }
        public string ipInternet { get; set; }
        public Nullable<System.DateTime> start_ { get; set; }
        public Nullable<System.DateTime> resign_ { get; set; }
        public Nullable<bool> isShow { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> LastActive { get; set; }
        public Nullable<bool> isConfirm { get; set; }
        public Nullable<bool> isInternet { get; set; }
        public string notify { get; set; }
        public string StatWork { get; set; }
        public string EmpInsert { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
        public string EmpUpdate { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
        public string RemarkUpdate { get; set; }
        public string Img { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> BalanceBrand { get; set; }
        public string Type_Level { get; set; }
        public string Type_Work { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Acc_Name { get; set; }
        public string Bank_Acc_No { get; set; }
        public string EmpEvaluation1 { get; set; }
        public string c_EmpEvaluation1_Group { get; set; }
        public string EmpEvaluation1_Group { get; set; }
        public string EmpEvaluation2 { get; set; }
        public string EmpHead { get; set; }
        public string NullEmp2 { get; set; }
        public string Shop { get; set; }
        public string Company { get; set; }
        public string c_FastSave { get; set; }
        public string Ref { get; set; }
        public string IsReplace { get; set; }
        public string text_Position { get; set; }
        public string email_2 { get; set; }
        public string Mobile { get; set; }
        public string Vcard_URL { get; set; }
        public string ISContact { get; set; }
        public string ISContact_Leave { get; set; }
    }
}
