//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Level
    {
        public string Type_Level { get; set; }
        public string Type_Name { get; set; }
        public Nullable<int> Type_Value { get; set; }
        public string Type_Head { get; set; }
        public Nullable<double> FC_Approve { get; set; }
        public Nullable<double> FC_Brand_Approve { get; set; }
    }
}
