//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsideSFG_WFEntities : DbContext
    {
        public InsideSFG_WFEntities()
            : base("name=InsideSFG_WFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BG_HApprove> BG_HApprove { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<BG_ForeCast> BG_ForeCast { get; set; }
        public virtual DbSet<Customer_Tax> Customer_Tax { get; set; }
        public virtual DbSet<BG_HApprove_Profitcenter> BG_HApprove_Profitcenter { get; set; }
        public virtual DbSet<WSHeadApproveBrand> WSHeadApproveBrands { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<Employee_Level> Employee_Level { get; set; }
        public virtual DbSet<POSITION> POSITIONs { get; set; }
        public virtual DbSet<vBrandAndHeadFC> vBrandAndHeadFCs { get; set; }
    }
}
