//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION
    {
        public int positionID { get; set; }
        public string position_ { get; set; }
        public string ePosition { get; set; }
        public Nullable<decimal> limitPay { get; set; }
        public string Flag { get; set; }
    }
}
