//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_Site
    {
        public string SiteStorage { get; set; }
    }
}
