//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBrandAndHeadFC
    {
        public string departmentID { get; set; }
        public string department_ { get; set; }
        public string UserID { get; set; }
        public string Flag { get; set; }
        public string Brand { get; set; }
        public string BRANDABB { get; set; }
        public string ID_Brand { get; set; }
        public string UserID_Approve { get; set; }
        public string ReserveGroupCompanyID { get; set; }
    }
}
