//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.InsideSFG_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSHeadApproveBrand
    {
        public string ID_Brand { get; set; }
        public string Brand { get; set; }
        public string Brand_Welfare { get; set; }
        public string BRANDABB { get; set; }
        public string ComCode { get; set; }
        public string UserID_Approve { get; set; }
        public string Remark { get; set; }
        public string Flag { get; set; }
        public string Flag_Sales { get; set; }
        public string Flag_WF { get; set; }
        public string Flag_SalesShop { get; set; }
        public string BM { get; set; }
        public string UserID_BM { get; set; }
        public string UserID_Asst { get; set; }
        public string EmpSave { get; set; }
        public Nullable<System.DateTime> Date_Save { get; set; }
        public string Cost_Center { get; set; }
        public string EForm_SCE_Sale_UserID { get; set; }
        public string EForm_SCE_BM_UserID { get; set; }
        public string Daily_Sales_Permission_UserID { get; set; }
        public string Daily_Sales_Flag { get; set; }
        public string UserID_Claim { get; set; }
        public string UserID_Approve_FingerScan { get; set; }
        public string Sale_UserID { get; set; }
        public string UserID_Asst_PS { get; set; }
        public string UserID_BM_PS { get; set; }
        public string UserID_Senior_PS { get; set; }
        public string UserID_MD_PS { get; set; }
        public string Flag_Clear { get; set; }
        public string UserID_Online_Commission { get; set; }
        public string UserID_Approve_Online_Com { get; set; }
        public string Flag_IO { get; set; }
    }
}
