//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Ecommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public int Channel_ID { get; set; }
        public string Channel_Name { get; set; }
        public string PrefixChannel { get; set; }
        public string Type_Transfer { get; set; }
        public string Type_Transaction { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> TerminalID { get; set; }
        public string PaymentTypeCode { get; set; }
        public string WMK_Channel_ID { get; set; }
        public string WMK_StorageWM { get; set; }
        public Nullable<bool> Flag_Status { get; set; }
        public Nullable<bool> Flag_Create { get; set; }
        public string Type_Company { get; set; }
        public string Pickup_Name { get; set; }
        public string Pickup_Address { get; set; }
        public string Pickup_City { get; set; }
        public string Pickup_Province { get; set; }
        public string Pickup_Postcode { get; set; }
        public string Pickup_Phone { get; set; }
        public string Pickup_Email { get; set; }
        public string Group_Type { get; set; }
        public Nullable<System.DateTime> Start_Event { get; set; }
        public Nullable<System.DateTime> End_Event { get; set; }
        public string Gateway_payment { get; set; }
    }
}
