//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Ecommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Orderitem
    {
        public string Docno { get; set; }
        public int No { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> PromoID { get; set; }
        public Nullable<double> retailPrice { get; set; }
        public Nullable<double> NetPrice { get; set; }
        public string Tracking_No { get; set; }
        public string Box_ID { get; set; }
        public Nullable<int> Unit_Box { get; set; }
        public Nullable<int> Channel_ID { get; set; }
        public Nullable<int> StatusItem_ID { get; set; }
        public Nullable<System.DateTime> POS_Date { get; set; }
        public Nullable<bool> Flag_Return { get; set; }
    }
}
