//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Ecommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Order
    {
        public string Docno { get; set; }
        public Nullable<System.DateTime> Date_Send { get; set; }
        public Nullable<int> StatusOrder_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<int> TransactionType_ID { get; set; }
        public string Ref_Order { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public string s_Name { get; set; }
        public string s_Phone1 { get; set; }
        public string s_Phone2 { get; set; }
        public string s_Address1 { get; set; }
        public string s_District_Name { get; set; }
        public Nullable<int> s_Province_ID { get; set; }
        public Nullable<int> s_City_ID { get; set; }
        public Nullable<int> s_PostCode { get; set; }
        public Nullable<int> s_Amphur_ID { get; set; }
        public Nullable<int> s_District_ID { get; set; }
        public string s_Address2 { get; set; }
        public Nullable<bool> Same_Address { get; set; }
        public Nullable<bool> b_Etax { get; set; }
        public string b_EmailEtax { get; set; }
        public string b_BranchID { get; set; }
        public string b_ID_Card { get; set; }
        public string b_Name { get; set; }
        public string b_Address1 { get; set; }
        public string b_Address2 { get; set; }
        public Nullable<int> b_District_ID { get; set; }
        public string b_District_Name { get; set; }
        public Nullable<int> b_City_ID { get; set; }
        public string b_City_Name { get; set; }
        public Nullable<int> b_Province_ID { get; set; }
        public string b_Province_Name { get; set; }
        public Nullable<int> b_PostCode { get; set; }
        public string b_Phone1 { get; set; }
        public string b_Phone2 { get; set; }
        public Nullable<int> b_Amphur_ID { get; set; }
        public Nullable<double> Shipping_Price { get; set; }
        public string Remark_Print { get; set; }
        public Nullable<System.DateTime> Date_Tracking { get; set; }
        public string UserID_Tracking { get; set; }
        public string Remark { get; set; }
        public string Url_QuickPay { get; set; }
        public Nullable<System.DateTime> Expiry_Payment { get; set; }
        public string P_qpID { get; set; }
        public string P_approvalCode { get; set; }
        public string P_referenceNo { get; set; }
        public Nullable<System.DateTime> P_transactionDateTime { get; set; }
        public string TrackingNo { get; set; }
        public string Docno_WMK { get; set; }
        public Nullable<bool> Shared_Customer { get; set; }
        public Nullable<bool> FB_Customer { get; set; }
        public string Short_URL { get; set; }
        public Nullable<int> InventoryDocID { get; set; }
        public Nullable<int> UserID_Commission { get; set; }
        public string Code_Commission { get; set; }
        public string Payment_ID { get; set; }
        public string Sitestorage { get; set; }
        public string RecheckEtax { get; set; }
    }
}
