//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Online_Lazada
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_Shopify_Items
    {
        public string AccountAPI { get; set; }
        public string variant_id { get; set; }
        public string product_id { get; set; }
        public string inventory_item_id { get; set; }
        public string sku { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> Date_Send { get; set; }
    }
}
