//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Online_Lazada
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_Key
    {
        public string Brand { get; set; }
        public string App_Name { get; set; }
        public string Email { get; set; }
        public string App_Key { get; set; }
        public string App_Secret { get; set; }
        public string AccessToken { get; set; }
        public string Url { get; set; }
        public string API_Path { get; set; }
        public string Code { get; set; }
        public string Status_Token { get; set; }
        public string Shop_ID { get; set; }
        public string refresh_token { get; set; }
        public Nullable<System.DateTime> refresh_expires_in { get; set; }
        public Nullable<System.DateTime> refresh_create { get; set; }
        public Nullable<System.DateTime> refresh_in { get; set; }
        public string StorageLocation { get; set; }
        public Nullable<int> Channel_ID { get; set; }
    }
}
