//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Online_Lazada
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_Shopify_GetOrderItems
    {
        public string AccountAPI { get; set; }
        public string ShopifyOrderID { get; set; }
        public string id { get; set; }
        public string sku { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> total_discount { get; set; }
    }
}
