//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Online_Lazada
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_Shopify_GetOrders
    {
        public string AccountAPI { get; set; }
        public string ID { get; set; }
        public string OrderID { get; set; }
        public string ShopifyOrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> OrderUpdatedDate { get; set; }
        public string order_number { get; set; }
        public string financial_status { get; set; }
        public string fulfillment_status { get; set; }
        public string s_Name { get; set; }
        public string s_Address1 { get; set; }
        public string s_Address2 { get; set; }
        public string s_City { get; set; }
        public string s_State { get; set; }
        public string s_Pincode { get; set; }
        public string s_Phone { get; set; }
        public string s_Email { get; set; }
        public string b_Name { get; set; }
        public string b_Address1 { get; set; }
        public string b_Address2 { get; set; }
        public string b_City { get; set; }
        public string b_State { get; set; }
        public string b_Pincode { get; set; }
        public string b_Phone { get; set; }
        public string b_Email { get; set; }
        public string Flash_outTradeNo { get; set; }
        public string Flash_pno { get; set; }
        public Nullable<bool> Flag_Item { get; set; }
        public Nullable<System.DateTime> Date_Send { get; set; }
        public Nullable<int> Channel_ID { get; set; }
        public Nullable<int> StorageWM_ID { get; set; }
        public string Docno { get; set; }
        public Nullable<double> shipping_price { get; set; }
    }
}
