//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Online_Lazada
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_Reference
    {
        public string FullTaxNo { get; set; }
        public string BillingNo { get; set; }
        public string FIDocNo { get; set; }
        public string FIDocCom { get; set; }
        public string FIDocYear { get; set; }
        public string OnlineRef { get; set; }
        public string SKU { get; set; }
        public Nullable<bool> Flaguse { get; set; }
        public int ItemLineNo { get; set; }
        public string DocHeader { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
    }
}
