//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.BC_TB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_Dimension
    {
        public string Dimension_Code { get; set; }
        public string Dimension_Name { get; set; }
        public Nullable<System.DateTime> Dimension_Modified_Last { get; set; }
        public string Dimension_ID { get; set; }
    }
}
