//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.BC_TB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BC_TBEntities : DbContext
    {
        public BC_TBEntities()
            : base("name=BC_TBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BC_Dimension> BC_Dimension { get; set; }
        public virtual DbSet<BC_Dimension_Values> BC_Dimension_Values { get; set; }
        public virtual DbSet<SiteSAP_BC> SiteSAP_BC { get; set; }
    }
}
