//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.BC_TB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSAP_BC
    {
        public string SiteSAP { get; set; }
        public string SiteBC { get; set; }
    }
}
