//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.SFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_VBRP_NEWSAP
    {
        public string BRAND { get; set; }
        public string VBELN { get; set; }
        public string POSNR { get; set; }
        public string MATNR { get; set; }
        public decimal KBMENG { get; set; }
        public string LGORT { get; set; }
        public string WERKS { get; set; }
        public string SPART { get; set; }
        public decimal WAVWR { get; set; }
        public decimal KZWI1 { get; set; }
        public decimal KZWI2 { get; set; }
        public decimal KZWI3 { get; set; }
        public decimal KZWI4 { get; set; }
        public decimal KZWI5 { get; set; }
        public decimal KZWI6 { get; set; }
        public decimal KBETR { get; set; }
        public string STYLE { get; set; }
        public string COLOR { get; set; }
        public string SIZE { get; set; }
        public System.DateTime DATE_FOR_CHECK { get; set; }
        public string SHOP_GR { get; set; }
    }
}
