//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.SFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_VBRK_NEWSAP
    {
        public string VBELN { get; set; }
        public string KUNRG { get; set; }
        public string KUNAG { get; set; }
        public string KNUMV { get; set; }
        public string AUART { get; set; }
        public System.DateTime VDATU { get; set; }
        public System.DateTime AUDAT { get; set; }
        public System.DateTime ERDAT { get; set; }
        public string VTWEG { get; set; }
        public string SPART { get; set; }
        public string ZOUNR { get; set; }
        public System.DateTime DATE_FOR_CHECK { get; set; }
        public string VKORG { get; set; }
        public string post_code { get; set; }
        public string Refdoc { get; set; }
        public string BKTXT { get; set; }
    }
}
