//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.SFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSAP_Site2
    {
        public string SiteStorage { get; set; }
        public string SITE { get; set; }
        public string BrandName { get; set; }
        public string SITENAME { get; set; }
        public string REGION { get; set; }
        public string LOCATION { get; set; }
        public string CHANNEL { get; set; }
        public string SITEGROUP { get; set; }
        public string TYPE { get; set; }
        public string GROUPSHOPTYPE { get; set; }
        public string SHOPTYPE { get; set; }
        public string POST { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    }
}
