//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Budget_2025
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Budget_2025Entities : DbContext
    {
        public Budget_2025Entities()
            : base("name=Budget_2025Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department_IO_2025> Department_IO_2025 { get; set; }
        public virtual DbSet<Department_IO_2025_Brand> Department_IO_2025_Brand { get; set; }
    }
}
