//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_Carrier_Log
    {
        public System.DateTime dateSend { get; set; }
        public string path { get; set; }
        public string status { get; set; }
        public string request { get; set; }
        public string respon { get; set; }
        public string fromFlash { get; set; }
    }
}
