//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculate_Car
    {
        public string DeliveryNumber { get; set; }
        public string BFID { get; set; }
        public string Docno { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> Date_Group { get; set; }
        public string TypeSendKO { get; set; }
    }
}
