//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarrierEntities : DbContext
    {
        public CarrierEntities()
            : base("name=CarrierEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article_Category> Article_Category { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Notify> Notifies { get; set; }
        public virtual DbSet<Order_Item> Order_Item { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Order_Box> Order_Box { get; set; }
        public virtual DbSet<Site_Profit> Site_Profit { get; set; }
        public virtual DbSet<Event_Shop> Event_Shop { get; set; }
        public virtual DbSet<Site_Center> Site_Center { get; set; }
        public virtual DbSet<History_Notify_Order> History_Notify_Order { get; set; }
    }
}
