//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrier_Api_Key
    {
        public int Api_No { get; set; }
        public string Transport_Type { get; set; }
        public string Url { get; set; }
        public string API_Key { get; set; }
        public string API_Secret { get; set; }
        public string UserID { get; set; }
        public string Email { get; set; }
        public string Userweb { get; set; }
        public string Pass { get; set; }
    }
}
