//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarrierEntities : DbContext
    {
        public CarrierEntities()
            : base("name=CarrierEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article_Category> Article_Category { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Notify> Notifies { get; set; }
        public virtual DbSet<Order_Item> Order_Item { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Order_Box> Order_Box { get; set; }
        public virtual DbSet<Site_Profit> Site_Profit { get; set; }
        public virtual DbSet<Event_Shop> Event_Shop { get; set; }
        public virtual DbSet<Site_Center> Site_Center { get; set; }
        public virtual DbSet<History_Notify_Order> History_Notify_Order { get; set; }
        public virtual DbSet<Status_Notify_Order> Status_Notify_Order { get; set; }
        public virtual DbSet<Comment_System> Comment_System { get; set; }
        public virtual DbSet<API_Carrier_Log> API_Carrier_Log { get; set; }
        public virtual DbSet<RunDocno> RunDocnoes { get; set; }
        public virtual DbSet<Order_Big_Box> Order_Big_Box { get; set; }
        public virtual DbSet<Calculate_Car> Calculate_Car { get; set; }
        public virtual DbSet<Lalamove_Import> Lalamove_Import { get; set; }
        public virtual DbSet<Flash_EX_Import> Flash_EX_Import { get; set; }
        public virtual DbSet<DHL_eCom_Import> DHL_eCom_Import { get; set; }
        public virtual DbSet<Carrier_Api_Key> Carrier_Api_Key { get; set; }
        public virtual DbSet<Lalamove_Car_DeliveryItemSpecification_Categories> Lalamove_Car_DeliveryItemSpecification_Categories { get; set; }
        public virtual DbSet<Lalamove_Car_DeliveryItemSpecification_HandlingInstructions> Lalamove_Car_DeliveryItemSpecification_HandlingInstructions { get; set; }
        public virtual DbSet<Lalamove_Car_DeliveryItemSpecification_Weight> Lalamove_Car_DeliveryItemSpecification_Weight { get; set; }
        public virtual DbSet<Lalamove_Car_Local> Lalamove_Car_Local { get; set; }
        public virtual DbSet<Lalamove_Car_PlaceOrder> Lalamove_Car_PlaceOrder { get; set; }
        public virtual DbSet<Lalamove_Car_Quotation> Lalamove_Car_Quotation { get; set; }
        public virtual DbSet<Lalamove_Car_SpecialRequests> Lalamove_Car_SpecialRequests { get; set; }
        public virtual DbSet<Lalamove_Car_Stop> Lalamove_Car_Stop { get; set; }
        public virtual DbSet<Lalamove_Car_Status> Lalamove_Car_Status { get; set; }
        public virtual DbSet<Lalamove_Location_Google_Temp> Lalamove_Location_Google_Temp { get; set; }
    }
}
