//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Central_Import
    {
        public System.DateTime Date_Create { get; set; }
        public string Date_Posting { get; set; }
        public string Shop { get; set; }
        public string Brand { get; set; }
        public string Profit { get; set; }
        public string Center { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Department_ID { get; set; }
        public string Docno_Budget { get; set; }
        public Nullable<decimal> Vat { get; set; }
    }
}
