//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_System
    {
        public int CM_ID { get; set; }
        public string CM_Message { get; set; }
        public Nullable<int> CM_Status { get; set; }
        public Nullable<System.DateTime> CM_DateCreate { get; set; }
    }
}
