//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Shop
    {
        public int Event_ID { get; set; }
        public string Shop_Code { get; set; }
        public string Event_Type { get; set; }
        public string Event_Branch { get; set; }
        public string Event_Name { get; set; }
    }
}
