//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flash_EX_Import
    {
        public string Docno { get; set; }
        public Nullable<System.DateTime> Date_Process { get; set; }
        public Nullable<System.DateTime> Date_Import { get; set; }
        public string pno { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> Status_Match { get; set; }
        public string Docno_Budget { get; set; }
        public Nullable<bool> Status_Budget { get; set; }
        public string Shop { get; set; }
        public Nullable<int> department_id { get; set; }
    }
}
