//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Notify_Order
    {
        public int History_ID { get; set; }
        public string History_NO { get; set; }
        public Nullable<System.DateTime> Date_Notify { get; set; }
        public string pno { get; set; }
        public string Docno { get; set; }
        public string Type_Send_KA { get; set; }
    }
}
