//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lalamove_Car_Stop
    {
        public string quotationId { get; set; }
        public string stopId { get; set; }
        public string coordinates_lat { get; set; }
        public string coordinates_lng { get; set; }
        public string address { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string remark { get; set; }
        public Nullable<int> StopNo { get; set; }
        public string Docno { get; set; }
    }
}
