//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lalamove_Car_PlaceOrder
    {
        public string OrderID { get; set; }
        public string quotationId { get; set; }
        public string driverId { get; set; }
        public string shareLink { get; set; }
        public string status { get; set; }
        public string BFID { get; set; }
        public Nullable<System.DateTime> Date_Status { get; set; }
        public string Status_Import { get; set; }
    }
}
