//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lalamove_Car_Local
    {
        public string Location_Code { get; set; }
        public string Location_name { get; set; }
        public string Car_Key { get; set; }
        public string Description { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Car_Load { get; set; }
        public string Car_Load_Unit { get; set; }
        public Nullable<System.DateTime> Date_save { get; set; }
        public string Car_Key_TH { get; set; }
        public string Description_TH { get; set; }
        public string Url_img { get; set; }
    }
}
