//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lalamove_Car_SpecialRequests
    {
        public int SpecialRequests_ID { get; set; }
        public string Location_Code { get; set; }
        public string Car_Key { get; set; }
        public string SpecialRequests_Name { get; set; }
        public string SpecialRequests_description { get; set; }
        public string SpecialRequests_Parent_type { get; set; }
        public Nullable<int> SpecialRequests_Max { get; set; }
        public Nullable<System.DateTime> SpecialRequests_Date_save { get; set; }
        public string SpecialRequest_Name_TH { get; set; }
    }
}
