//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lalamove_Car_Quotation
    {
        public string quotationId { get; set; }
        public Nullable<System.DateTime> scheduleAt { get; set; }
        public Nullable<System.DateTime> expiresAt { get; set; }
        public string serviceType { get; set; }
        public Nullable<double> priceBreakdown_total { get; set; }
        public Nullable<int> item_quantity { get; set; }
    }
}
