//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lalamove_Car_DeliveryItemSpecification_HandlingInstructions
    {
        public int DeliveryItemSpecification_handlingInstructions_id { get; set; }
        public string Location_Code { get; set; }
        public string Car_Key { get; set; }
        public string DeliveryItemSpecification_handlingInstructions { get; set; }
        public Nullable<System.DateTime> Date_Save { get; set; }
        public string DeliveryItemSpecification_handlingInstructions_TH { get; set; }
    }
}
