//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lalamove_Import
    {
        public string Delivery_ID { get; set; }
        public Nullable<System.DateTime> Date_Complete { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> Status_Match { get; set; }
    }
}
