//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lalamove_Location_Google_Temp
    {
        public System.DateTime datecreate { get; set; }
        public string Userid { get; set; }
        public string Address_In { get; set; }
        public string Address_Out { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public string path { get; set; }
        public string BFID { get; set; }
    }
}
