//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notify
    {
        public string TicketPickupId { get; set; }
        public Nullable<int> StaffInfoId { get; set; }
        public string StaffInfoName { get; set; }
        public string StaffInfoPhone { get; set; }
        public string UpCountryNote { get; set; }
        public string TimeoutAtText { get; set; }
        public string TicketMessage { get; set; }
        public Nullable<System.DateTime> DateNotify { get; set; }
        public string warehouseNo { get; set; }
    }
}
