//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Big_Box
    {
        public int RunID { get; set; }
        public string BFID { get; set; }
        public string Docno { get; set; }
        public string Status { get; set; }
        public string StatusNotifyCode { get; set; }
        public string StatusNotifyText { get; set; }
        public string StatusCal { get; set; }
        public string Lala_Car_Key { get; set; }
        public string Lala_Car_Status { get; set; }
        public string status_Auto { get; set; }
        public Nullable<System.DateTime> DateSend_Mail { get; set; }
        public string SpecialRequests_Name { get; set; }
        public string Remark_Driver { get; set; }
        public Nullable<decimal> Price_Lala { get; set; }
    }
}
