//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string Docno { get; set; }
        public Nullable<System.DateTime> Date_send { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ExpressCategory { get; set; }
        public Nullable<int> Owner_ID { get; set; }
        public Nullable<int> StorageWM_ID { get; set; }
        public Nullable<int> Channel_ID { get; set; }
        public string Ref_Order { get; set; }
        public string srcName { get; set; }
        public string srcPhone { get; set; }
        public string srcProvinceName { get; set; }
        public string srcCityName { get; set; }
        public string srcDistrictName { get; set; }
        public string srcPostalCode { get; set; }
        public string srcDetailAddress { get; set; }
        public string dstName { get; set; }
        public string dstPhone { get; set; }
        public string dstHomePhone { get; set; }
        public string dstProvinceName { get; set; }
        public string dstCityName { get; set; }
        public string dstDistrictName { get; set; }
        public string dstPostalCode { get; set; }
        public string dstDetailAddress { get; set; }
        public Nullable<int> articleCategory { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> insured { get; set; }
        public string remark { get; set; }
        public string status { get; set; }
        public Nullable<int> Transport_Type { get; set; }
        public string SDpart { get; set; }
        public string saleOn { get; set; }
        public string siteStorage { get; set; }
        public string saleChannel { get; set; }
        public Nullable<int> TypeSend { get; set; }
    }
}
