//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Profit
    {
        public string Brand { get; set; }
        public string Channel { get; set; }
        public string COMCODE { get; set; }
        public string Profit { get; set; }
        public string Costcenter { get; set; }
        public string Site_Stroage { get; set; }
        public string Sale_Channel { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
    }
}
