//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Model.Carrier
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_View
    {
        public string UserID_H { get; set; }
        public string UserID_S { get; set; }
        public Nullable<System.DateTime> dateAdd { get; set; }
    }
}
